# wrangler.toml
name = 'santrionlineapp'
compatibility_date = "2024-11-19"
pages_build_output_dir = ".svelte-kit/cloudflare"

# --- Konfigurasi Database D1 ---
[[d1_databases]]
binding = "DB" # Ini nama variabel yang akan kita panggil di kodingan (misal: platform.env.DB)
database_name = "db-app"
database_id = "9c7b8ab4-8e7a-406d-9e44-6da413d7d9e0"

# --- Konfigurasi R2 Storage ---
[[r2_buckets]]
binding = "BUCKET" # Ini nama variabel untuk storage (misal: platform.env.BUCKET)

bucket_name = "santri-online-files"
